In [213]:
import numpy as np

A freelancer charges 60 euros/hour, works between 6 and 8 hours a day, 4 and 5 days a week.<br />
He usually earns between 1.350 and 2.300 euros a month, 15.000 and 25.000 euros a year.<br />
Using data from 'freel.csv', find:<br />
- The 
- The 

In [214]:
all_wages = []
for _ in range(5):
    wage = np.random.randint(1400, 2301, size=12, dtype=np.int16)
    all_wages.append(wage)
npwage = np.array(all_wages)
print(npwage)


[[2013 2058 1638 2198 2201 1436 1855 1932 1994 1531 1745 1665]
 [2034 1400 1528 2250 2074 2005 2127 2057 2146 2054 1675 2279]
 [1760 1446 1857 2104 2004 1468 2182 1543 1992 1924 1870 1701]
 [1615 2094 1430 2104 1685 2130 1476 1849 1427 2224 1451 1430]
 [2070 1442 2052 1774 1661 1864 2298 1487 2003 2014 2009 1729]]


#### find min / max / avg

In [215]:
# min by sample (row)
smin = np.min(npwage, axis=1)
print(f'min by sample {smin} -> {np.mean(smin)}')
# min by month (col)
mmin = np.min(npwage, axis=0)
print(f'min by month {mmin} -> {round(np.mean(mmin), 2)}')


min by sample [1436 1400 1446 1427 1442] -> 1430.2
min by month [1615 1400 1430 1774 1661 1436 1476 1487 1427 1531 1451 1430] -> 1509.83


In [216]:
# max by sample (col)
smax = np.max(npwage, axis=1)
print(f'max by sample {smax} -> {round(np.mean(smax), 2)}')
# max by month (col)
mmax = np.max(npwage, axis=0)
print(f'max by month {mmax} -> {round(np.mean(mmax), 2)}')


max by sample [2201 2279 2182 2224 2298] -> 2236.8
max by month [2070 2094 2052 2250 2201 2130 2298 2057 2146 2224 2009 2279] -> 2150.83


In [217]:
# average by sample (row)
saverage = np.mean(npwage, axis=1, dtype=np.int16)
print(f'avg by sample {saverage} -> {round(np.mean(saverage), 2)}')
# average by month (col)
maverage = np.mean(npwage, axis=0, dtype=np.int16)
print(f'avg by month {maverage} -> {round(np.mean(maverage), 2)}')


avg by sample [1855 1969 1820 1742 1866] -> 1850.4
avg by month [1898 1688 1701 2086 1925 1780 1987 1773 1912 1949 1750 1760] -> 1850.75


#### find where he reached the 2.000/mo income cap

In [218]:
print(npwage > 2000)
print(f'reached {npwage[npwage > 2000].size} times out of {npwage.size}')

[[ True  True False  True  True False False False False False False False]
 [ True False False  True  True  True  True  True  True  True False  True]
 [False False False  True  True False  True False False False False False]
 [False  True False  True False  True False False False  True False False]
 [ True False  True False False False  True False  True  True  True False]]
reached 26 times out of 60
