In [ ]:
import numpy as np

In [ ]:
# print your numpy version

print(np.__version__)

In [ ]:
# Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

# random
arr = np.random.randint(2, 11, size=(3, 3))
print(arr)
# even
arr = np.arange(2, 11).reshape(3, 3)
print(arr)

In [ ]:
# Write a NumPy program to create a 2d array with 1 on the border and 0 inside

arr = np.ones((3, 5), dtype=int)
print(arr)
ar0 = np.zeros((3), dtype=int)
print(ar0)
arr[1, 1:4] = ar0
print(arr)

In [ ]:
#  Write a NumPy program to add a border (filled with 0's) around an existing array

arr = np.ones((3, 3), dtype=int)
print(arr)
ar0 = np.zeros((5, 5), dtype=int)
print(ar0)
ar0[[1, 2, 3], 1:4] = arr
print(ar0)

In [ ]:
# Extract all odd numbers from arr
arr = np.random.randint(51, size=10, dtype=np.int8)
print(arr)
print(arr[arr % 2 == 1])

# Replace them with -1
arr[arr % 2 == 1] = -1
print(arr)

In [ ]:
# Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)
c = np.concatenate((a, b), axis=0)  # `axis=1` to stack horizontally
print(c)

In [ ]:
# Repeat element within an array
a = np.array([1,2,3])

# successively repeat an element x times
print(np.repeat(a, 3))  # or just print(a.repeat(3))

# successively repeat the whole sequence x times
print(np.tile(a, 3))
# put them together
np.r_[np.repeat(a, 3), np.tile(a, 3)]

In [ ]:
# From array 'a' remove all items present in array 'b'
# NOTE it returns non-repeated values
## a = np.array([1,2,3,4,5,6])
## b = np.array([4,5,6,7,8,9])
## np.setdiff1d(a, b)

# randomly
# here we randomly genrate two sets of unoque values
a = np.random.choice(range(101), size=20, replace=False)
print(a)
b = np.random.choice(range(101), size=20, replace=False)
print(b)
# we look in 'b' for values that are not in 'a' 
c= np.setdiff1d(a, b, assume_unique=False)
print(c, c.size)
# if for some reason you would like to see
# the ones that actually are
d = np.intersect1d(a, b)
print(d, d.size)

In [ ]:
# Get the positions where elements of a and b match
a = np.arange(4, 10, dtype=np.int8)
b = np.arange(2, 14, 2, dtype=np.int8)
print(a)
print(b)
c = np.where(a == b)
print(c)

In [ ]:
# Get all items between 5 and 10 from a
a = np.random.randint(11, size=10, dtype=np.int8)
print(a)
i = np.where((a >= 5) & (a <= 10))
print(a[i])
# or i = np.where(np.logical_and(a>=5, a<=10))
# or simply
a[(a >= 5) & (a <= 10)]


In [ ]:
# 
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
c = np.max((a, b), axis=0)
c

In [ ]:
# Swap two columns (1 and 2) in the array arr
arr = np.arange(-4, 5).reshape(3,3)
# print(arr)
# print(arr[:, [1, 0, 2]])

# Swap two rows (2 and 3) in the array arr
# print(arr[[0, 2, 1], :])

# Swap all rows in an array
a = np.random.choice(range(-7, 9), size=(4, 4), replace=False)
print(a)
# print(np.flip(a, axis=0))     # or np.flipud(a)
# or print(a[::-1])

# Swap all cols in an array
print(np.fliplr(a))       # or np.flip(a, axis=1)
# or print(a[:, ::-1])

In [311]:
# Create a 2D array of shape 5×3 to contain random 
# decimal numbers between 5 and 10
a = np.random.randint(5, 10, size=(5, 3)) + np.random.random((5, 3))
print(a)
# or
b = np.random.uniform(5, 10, size=(5, 3))
print(b.shape)
# optionally limit the output to n decimals
np.set_printoptions(precision=3)

[[6.84  8.888 5.555]
 [5.206 9.142 6.158]
 [8.479 9.377 6.442]
 [9.323 9.16  8.789]
 [7.68  5.265 9.075]]
(5, 3)
