In [ ]:
import numpy as np

In [ ]:
a = np.arange(1, 31, dtype=np.int8).reshape(6, 5)
print(a)

[ 1  2  3  4  5]<br />
[ 6  7  8  9 10]<br />
[11 12 13 14 15]<br />
[16 17 18 19 20]<br />
[21 22 23 24 25]<br />
[26 27 28 29 30]<br />

In [ ]:
# index the submatrix [[11, 12], [16, 17]]
sub_a = a[2:4, :2]  # or sub_a = a[[2, 3], :2]
print(sub_a)


In [ ]:
# index the submatrix [[4, 5], [24, 25], [29, 30]]
sub_b = a[[0, 4, 5], 3:]
print(sub_b)


In [ ]:
# index the submatrix [[1], [7], [13], [19], [25]]
sub_c = a[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
print(sub_c.reshape(5, 1))

In [ ]:
# index the submatrix [[3], [6], [12], [24]]
sub_d = a[[0, 1, 2, 4], [2, 0, 1, 3]]
print(sub_d.reshape(4, 1))


In [ ]:
# indexing the submatrix [[18, 28], [19, 29]]
sub_e = a[[3, 3, 5, 5], [2, 3, 2, 3]]
print(sub_e.reshape(2, 2))