#### Statistics functions in Numpy

In [1]:
import numpy as np
from rich import print

#### @Arithmetic Mean
arithmetic mean = sum of all elements / number of elements

In [ ]:
# find the arithmetic mean of a 1-d array
a = np.random.randint(3, 7, size=3, dtype=np.int8)
# print(a)
# print(np.mean(a))
# find the arithmetic mean of a 2-d array
ab = np.random.randint(1, 9, size=(3, 2), dtype=np.int8)
# print(ab)
# print(np.mean(ab))
# find the arithmetic mean of a specific axis
abc = np.random.randint(-3, 3, size=(4, 3), dtype=np.int8)
abc
print(np.mean(abc, axis=0))

#### @Max / Min

In [ ]:
b = np.random.randint(-2, 3, size=5, dtype=np.int8)
# print(b)
# print(np.max(b))
# print(np.min(b))
# find the max/min value(s) of a specific 
# axis in a ndarray
ba = np.random.randint(-1, 1, size=(4, 3), dtype=np.int8)
print(ba)
print(np.max(ba, axis=1))    # max value of each row
print(np.min(ba, axis=0))    # min value of each col

#### @Sum

In [34]:
c = np.random.randint(-2, 3, size=5, dtype=np.int8)
# print(c)
# print(np.sum(c))
# again you can specify an axis
ca = np.random.randint(-1, 2, size=(4, 3), dtype=np.int8)
print(ca)
print(np.sum(ca, axis=1))   # sum of each row
print(np.sum(ca, axis=0))   # sum of each col

[[-1 -1  1]
 [-1 -1  0]
 [ 0  1  0]
 [ 0  1  1]]
[-1 -2  1  2]
[-2  0  2]
